abstract class NewsStates {}
class NewsInitialState extends NewsStates{}
class NewsBottomNavigationBarState extends NewsStates{}
class NewsLoadingState extends NewsStates{}
class NewsBusinessSuccessState extends NewsStates{}
class NewsBusinessErrorState extends NewsStates{}
class NewsScienceSuccessState extends NewsStates{}
class NewsScienceErrorState extends NewsStates{}
class NewsSportsSuccessState extends NewsStates{}
class NewsSportsErrorState extends NewsStates{}
class NewsSearchSuccessState extends NewsStates{}
class NewsSearchErrorState extends NewsStates{}
class NewsThemeModeState extends NewsStates{}